"""initial

Revision ID: 2a3369d396fe
Revises: 
Create Date: 2025-05-09 17:28:28.721331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3369d396fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conf_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=45), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('photo', sa.String(length=256), nullable=True),
    sa.Column('cores', sa.Integer(), nullable=True),
    sa.Column('cpu_freq', sa.Float(), nullable=True),
    sa.Column('gpu_cores', sa.Integer(), nullable=True),
    sa.Column('cuda', sa.Integer(), nullable=True),
    sa.Column('gpu_freq', sa.Integer(), nullable=True),
    sa.Column('ram_mem', sa.Integer(), nullable=True),
    sa.Column('ram_freq', sa.Integer(), nullable=True),
    sa.Column('memory', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cores', sa.Integer(), nullable=True),
    sa.Column('cpu_freq', sa.Float(), nullable=True),
    sa.Column('gpu_cores', sa.Integer(), nullable=True),
    sa.Column('cuda', sa.Integer(), nullable=True),
    sa.Column('gpu_freq', sa.Integer(), nullable=True),
    sa.Column('ram_mem', sa.Integer(), nullable=True),
    sa.Column('ram_freq', sa.Integer(), nullable=True),
    sa.Column('memory', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os', sa.String(length=45), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('photo', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('id_conf', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_conf'], ['configuration.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vm_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vm_id'], ['vm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vm_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.String(length=12), nullable=True),
    sa.Column('date_finish', sa.String(length=12), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vm_id'], ['vm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vm_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('payment_info', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vm_id'], ['vm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ssh_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vm_id', sa.Integer(), nullable=True),
    sa.Column('key_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vm_id'], ['vm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ssh_key')
    op.drop_table('payment')
    op.drop_table('deal')
    op.drop_table('cart')
    op.drop_table('vm')
    op.drop_table('user')
    op.drop_table('configuration')
    op.drop_table('conf_template')
    # ### end Alembic commands ###
